creation_rules:
  - path_regex: .*\.(yaml|yml|json|tf|tfvars)$
    encrypted_regex: ^(data|stringData|password|token|key|secret|content)$
    age: age1wgsnca8gljfz2659cs8rmme7aanwznkdakck32qmeks7sslec50svgdjwv
