creation_rules:
  - path_regex: config/cluster_config\.yaml$
    encrypted_regex: ^(name|ip|username|owner|repository|ips|node|cores|memory|disk_size|gateway|subnet|dns)$
    age: age1wgsnca8gljfz2659cs8rmme7aanwznkdakck32qmeks7sslec50svgdjwv
  - path_regex: .*\.(yaml|yml|json|tf|tfvars)$
    encrypted_regex: ^(data|stringData|password|token|key|secret|content|api_url|token_id|api_token)$
    age: age1wgsnca8gljfz2659cs8rmme7aanwznkdakck32qmeks7sslec50svgdjwv
