apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
  namespace: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      securityContext:
        # user is 1000, node
        fsGroup: 1000 
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:2.19.5
          ports:
            - containerPort: 3005
          securityContext:
            allowPrivilegeEscalation: false
          envFrom:
            - configMapRef:
                name: audiobookshelf-configmap
          volumeMounts:
            - name: audiobookshelf-audiobooks
              mountPath: /audiobooks
            - name: audiobookshelf-podcasts
              mountPath: /podcasts
            - name: audiobookshelf-config
              mountPath: /config
            - name: audiobookshelf-metadata
              mountPath: /metadata
      volumes:
        - name: audiobookshelf-audiobooks
          persistentVolumeClaim:
            claimName: audiobookshelf-pvc-audiobooks
        - name: audiobookshelf-podcasts
          persistentVolumeClaim:
            claimName: audiobookshelf-pvc-podcasts
        - name: audiobookshelf-config
          persistentVolumeClaim:
            claimName: audiobookshelf-pvc-config
        - name: audiobookshelf-metadata
          persistentVolumeClaim:
            claimName: audiobookshelf-pvc-metadata
