# Talos Kubernetes cluster configuration
# Centralized source of truth for both Terraform and Talos scripts
# Physical host management
physicalHosts:
    - name: ENC[AES256_GCM,data:UfGcJHduECqQsSW//pQ=,iv:tIBN9gR8ahiXLCUfI/OY1MHOyC7bOfUuhmscngYjFyo=,tag:UnDPnr9zeJwXYp+VgRv3+A==,type:str]
      username: ENC[AES256_GCM,data:mng9Zk8=,iv:9XwRPTJ12n/3NL5KbJqmc++Ms+rJMRjF/WtxskKdfB4=,tag:Dr/I8Hfy0i7v3wlcxhok5w==,type:str]
      ip: ENC[AES256_GCM,data:hZ1jxuGqULRCSxR2Og==,iv:Bt5Ao7VSaYkuUyQavKQRBfshPUpbnO3q95cmajtP+8M=,tag:k+Tv9friUCKPlQYXs8s0uw==,type:str]
    - name: ENC[AES256_GCM,data:0PoNXuP5kZL5zceR,iv:sJTAMvNeirTNQrirWO9+y/1kVFOb+9ax1G/B8rbhSOI=,tag:R+yndAQNoCaxdnpUw9clnQ==,type:str]
      username: ENC[AES256_GCM,data:UbNj7/NhRvgwgI3Z,iv:BrZ9sntCbLfqdvhPlvsUDxeyPn1+pxthfZpeA7AWj+M=,tag:Z7zi1j/bsDlkLpVXR1VvPg==,type:str]
      ip: ENC[AES256_GCM,data:pOZjHY9u9Dd7PqLWVA==,iv:sMUsKfaaIdL7z52hI/rk3Jma2fLTomL5uYjoySfQpaE=,tag:gtIJlU/wgjQxkxx5K0Vxmw==,type:str]
    - name: ENC[AES256_GCM,data:XnbvdKu8LUlMYmYh,iv:Q7vbT/ijWUBjPyjRnNzWw1Q0bsDT5iVVPyq5Ov+06Bs=,tag:UF2vxYjKkdX40o0K4YbNEw==,type:str]
      username: ENC[AES256_GCM,data:v9vX37iCZWprVxkc,iv:xs5S6n1ZtTiG5QD5vLtIyIfhIYvlNlgQ90YnKFIluY0=,tag:ONJqLCsn+ZCpiPtN8eT/Lw==,type:str]
      ip: ENC[AES256_GCM,data:L57eJT18AefZMbuSxA==,iv:WFYzvUXafhesUpQUe4DmrEnRbB+0yghDzOlA3RSS6z8=,tag:Ej5SzwGOz9BHAhwedUZlBQ==,type:str]
    - name: ENC[AES256_GCM,data:V/nN0Ta/qW0eDA==,iv:7Yw41wyr+xsSAwMT9bY98wslYwkQnjMXl7XrnnUD0mA=,tag:uXXjo5gxbER06tyDVc5VoA==,type:str]
      username: ENC[AES256_GCM,data:U76jGZtXQ5AcUg==,iv:bF83LvbnE4lWyZrKdpsnKONAMpOYe5BNNGIziNiMLkY=,tag:3BH020tkGN4A0Ecx9cfJ9Q==,type:str]
      ip: ENC[AES256_GCM,data:K6F252qw5G49Nxny2Q==,iv:vavC62tQ9Pk9QGV7gxxeXy0Zal+m/lvaEDncBhnxvA0=,tag:sLh6fwsxVAEgmxpnm42wVg==,type:str]
# Cluster metadata
clusterName: talos-k8s-cluster
talosVersion: v1.9.5
# Can be 'staging' or 'production'
environment: staging
gitRepo:
    owner: ENC[AES256_GCM,data:2BDIPs72XGsOOK6d,iv:QIyieOoS6GJ2MedmpYUnEcw7l6XQ/JgEkzrB38UBsrQ=,tag:6jCnTsHqxAEel3DfXEnPzA==,type:str]
    repository: ENC[AES256_GCM,data:0v9dI+B97Q==,iv:zRemyPWmlH7kfddIP+z2eaSWtNdNFXYxtB14JjTxQtU=,tag:bgyBGzuq1z71b+qS5Mv9yQ==,type:str]
# Control plane configuration
controlPlanes:
    count: 3
    ips:
        - ENC[AES256_GCM,data:kZbykq122YhIN9RiqA==,iv:cIp0k/rhugCaAzjGO9JZE+yvOe6tNJTTurd/g+u79YQ=,tag:FeX39D6w/kt5Gdq4VtxwHQ==,type:str]
        - ENC[AES256_GCM,data:JMVmySEfgzElLr4MbQ==,iv:5GZE8J4XBq5UST3U25iGQK4yK+TK3c+wROtygqQCk9w=,tag:zaY+ClgDtn3K/hm1ji+4IQ==,type:str]
        - ENC[AES256_GCM,data:fDI+IKcGba7XUryDQg==,iv:/Eqs0mf0fqAF3yPGz9ksAd/7X0tmyj1AAhmT9fdem5g=,tag:mJk92XZPJSTkJb+Q4eh90Q==,type:str]
    # Maps to the index in ips array
    profiles:
        # Primary
        - node: ENC[AES256_GCM,data:GG3+AKikxLJb6UZ/,iv:3ybAgSmbCdBDKWZ3iuJK/A+xCkIAyB2EJ3tI57s0x0g=,tag:yCGQ4IfxFmVB1w5zsQR07A==,type:str]
          cores: ENC[AES256_GCM,data:TA==,iv:hdJ0k1VLGyZmZ6Ow0g2orNlvvmSVOnZEhSWpLIcAwlE=,tag:e6yGkzzHWsI4NAm3kpMTrA==,type:int]
          memory: ENC[AES256_GCM,data:gpSJPg==,iv:pRIXplwhCvDNeF01mZ4Ptxg8isBRxjWhJUnwAb584JI=,tag:f4sCM+kzjGOw2x0xKK9CCg==,type:int]
          disk_size: ENC[AES256_GCM,data:RA1v,iv:iJJi+l+lqfDfnZuYnWvDBdXo71jOMnT6pH+pgDEbj98=,tag:JygTuifbscaKU3tyJbXanA==,type:str]
        # Secondary
        - node: ENC[AES256_GCM,data:2k4hFBYBCIMNgCeT,iv:wMk6cMAXc2UTSrC9Yd4MNf5HVPq/LmZ/6bgaCfUdPA0=,tag:IU2XjpQiEv0a+mRHISHf4g==,type:str]
          cores: ENC[AES256_GCM,data:qg==,iv:t6gBBB0/oZ2flgMGVw/HGpLEhIaHNRlVIhmWpnyTKr4=,tag:VcZGMTXcwm4yPJmiHxNy3w==,type:int]
          memory: ENC[AES256_GCM,data:QSn0TA==,iv:1M/EAMHKSvabVeHUHe+zw9KEYFodg+IWBjjmezcYKng=,tag:KD8ruFhNlOQPz0NTwsCtXQ==,type:int]
          disk_size: ENC[AES256_GCM,data:kWUk,iv:9RF3LAg7Vru0wNHJgAwL6NHCxTRjEZrfAb8FzNA6Jko=,tag:HYi8GhkSmoj4sHSJo7B5dA==,type:str]
        # Tertiary
        - node: ENC[AES256_GCM,data:Uzv6w2DjxMDXkr+Chqc=,iv:uTmfcoG+w/1A7SCW5Wswvk9MGofeX9tF6kUrPP/zxcY=,tag:L+Fs3BCnXBZPgkL+M/uKXA==,type:str]
          cores: ENC[AES256_GCM,data:VA==,iv:hREwD24JtDLPe3pHd0D9RBDP7qoAiIj9nlk+w2eypPE=,tag:NL2rIIYpT2k5yLD1EOFpyg==,type:int]
          memory: ENC[AES256_GCM,data:BvT7Qg==,iv:LPYFamIiWfHUgAeP4SlMbTDJ53UkVxglhPaJvz4SEBw=,tag:j/BhnPg7FJKZ3NoRy4K4Jw==,type:int]
          disk_size: ENC[AES256_GCM,data:+4uc,iv:FFdLc2nQbTHE0BDaD1Stw/KhENs7+PL3GchFxnvZ94I=,tag:lBKPrIsKGxHBT6YDX1iJDQ==,type:str]
# Worker node configuration
workers:
    count: 4
    ips:
        - ENC[AES256_GCM,data:dnrPuhFO7gwsRU0yrg==,iv:m8Egxv1wIFDgTOVt5xatK0RT1PcNmkp/CdGztDYROiQ=,tag:brwUWYZC/wWXHgF5n80XSA==,type:str]
        - ENC[AES256_GCM,data:vUvQhfnkNniQ+miqGw==,iv:ndx3d4N7C0o2kcZCaB47fvaioaHkzvXsOZS7XQWS0JQ=,tag:8EqXJRAgxQGbxjkvB8coSQ==,type:str]
        - ENC[AES256_GCM,data:k+goCIF5yq4mA+aB4g==,iv:F1dhcRe0CnOTyNonX6enymCKLP+quQWHKfKkPYvPCz0=,tag:/iCM5RKffjY7sQah3HfVGQ==,type:str]
        - ENC[AES256_GCM,data:M50czXjaKjdrt8QHQQ==,iv:ObIvP0CKQpQPk7VBBeprIWoqE6hdAVrBvWXU8XwJIJI=,tag:cfXZbbzxAscSL73xj/7ewA==,type:str]
    # Maps to the index in ips array
    profiles:
        # Worker 1
        - node: ENC[AES256_GCM,data:OijTzqFlJ5hkvZf7,iv:RdgurunKuUSSnAcrgmGH5ecJLNgrMIBfbdp3wy4GT6M=,tag:kSI1/IxpSY91c+yRSvKy2g==,type:str]
          cores: ENC[AES256_GCM,data:xQ==,iv:xIh9zVETCB48yNsHoER0yKcXcg+Dgt6WmkafSJxPR7w=,tag:hkOykH1c9w6Qao5tOnniyg==,type:int]
          memory: ENC[AES256_GCM,data:vKScWw==,iv:LDwC7e41NFk3v3qNFIbLhcG61geMc2d3xwXOfEx+k7c=,tag:wxNgZNYPayAJSgUrfBb8wA==,type:int]
          disk_size: ENC[AES256_GCM,data:glYG,iv:coXyYFmM6h3tpDuAXsVp7uXBlrxeDaiLPg1GUPFmIX8=,tag:hDCbTB9bmV1wm4Uvmf8SDw==,type:str]
        # Worker 2
        - node: ENC[AES256_GCM,data:8DxVeK/H4db/LKGF,iv:95X0w31Kzh4bEoADKyVcdq47ZExZNYtbEfFGZCIgRC4=,tag:cAxce8HivC94gFbJt/49DQ==,type:str]
          cores: ENC[AES256_GCM,data:fg==,iv:VW47JRxkRYLIpFIl8GyIHWlwIIMcaF0qUq8udZqP/qQ=,tag:qP7rdiFYS6wlOsc2WbivZw==,type:int]
          memory: ENC[AES256_GCM,data:YcnJTQ==,iv:63kXMF/blX8o7nR3NThbBM/Ll7N/l4ema6XCIJ3BO0s=,tag:U0cTete080HC75R2T7PsJQ==,type:int]
          disk_size: ENC[AES256_GCM,data:F/Tm,iv:slKnNfhkejoNJLF3fyNvO9ZXshyrJcPLKM6ypPHMDgI=,tag:x+60GL+yzEuCHOOZ9A5l1A==,type:str]
        # Worker 3
        - node: ENC[AES256_GCM,data:fwlHP1TQVIZVIqEN,iv:zD5FH0inHI+4DwSunYOHbf8cqCtCMx4oSxnPdn0V+VA=,tag:QHJFf3uKkG9/kpFdfERaKw==,type:str]
          cores: ENC[AES256_GCM,data:5A==,iv:ZjfTbA5dezqWaCvZsmL3VtT7u/8CAYKCizXlZV37fv0=,tag:/rfWe2WlXXwdGzMNw+ULAg==,type:int]
          memory: ENC[AES256_GCM,data:8yJ+Lg==,iv:zJTQQF51tVHWNUrl7ffwWZHK3Bg8dY6OY18/ZIlT8wI=,tag:4WfkUMuZ5E12VjuLphmUYA==,type:int]
          disk_size: ENC[AES256_GCM,data:cMGT,iv:d5AAvLGiG69asPbGJWHb4psix/WZMPQYKpIK8tBgT1k=,tag:m/0n/qo4atKI5mtVRaO69g==,type:str]
        # Worker 4
        - node: ENC[AES256_GCM,data:kWUepgOns5DRcA==,iv:r1mDRLA5L7p95DZ1a6V3bRio4qy01uqMPzNaQTO6niw=,tag:YRndVU9McQ5w7RB0cgxqmw==,type:str]
          cores: ENC[AES256_GCM,data:qg==,iv:v3nG4Uv5wXTXG183xYr1RKzi3zT2i97fRDurQQ7x190=,tag:/7FP70E5IP7wJ2vWhH4XrQ==,type:int]
          memory: ENC[AES256_GCM,data:m7Dk/A==,iv:oJkmLhUQAJVGdm3tPbyd+q88PBMt3nscIDrl/Qn0sso=,tag:ozRdCecS6mKHZ/wQljy+5g==,type:int]
          disk_size: ENC[AES256_GCM,data:7Fnr,iv:6sB/rwz49h2HASVfUgbCFcZYZZa9orBlxtWi+APqRaE=,tag:5g9aZFHSHqUggSWhx3A/ig==,type:str]
# Network configuration
network:
    gateway: ENC[AES256_GCM,data:/F60aqUGFNWbG4c=,iv:OrhuRn2d4SSwnJdlynbt1OXndH2skqJwyvzQi9JQsvw=,tag:0g1G9C0aeWJ9BNHeiT3YJg==,type:str]
    subnet: ENC[AES256_GCM,data:Arhrl2Iu5+mgJQ/mRsc=,iv:/NGjbEuFJtRlA9j0ele9Ut2SmhT2q85zjH54PK2R0C8=,tag:Oh6Zdv7Oq4EVi3kwRyqXzg==,type:str]
    dns:
        - ENC[AES256_GCM,data:7MlG4KtFiAW2MG4=,iv:cXz2mXPOvHjdir4xiU7l5uBSdZAvEpnoxMKh8IgzgJo=,tag:q2UlOArhWU80PrzBfikJ2A==,type:str]
        - ENC[AES256_GCM,data:c1MGSfoKqA==,iv:D9Op6H2qNjxX2woowRVuF0+yRMWfLpqVBvXzhX6hVyE=,tag:mLS2riSghSltZZxt9xxIaw==,type:str]
# Storage configuration
storage:
    # NFS path for ISOs in Proxmox
    isoPath: iso-nfs:iso
    # Storage location for VM disks
    vmDiskStorage: local
sops:
    age:
        - recipient: age1wgsnca8gljfz2659cs8rmme7aanwznkdakck32qmeks7sslec50svgdjwv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDR0VGdDQ4dUhJcnMvQ2lw
            TDVPY1o4aDduTThsSm1jdjlYY2oxN0VkQTBnCmRINmJTS3p2K3hZejFzVEx0MDBW
            bEc3bTFFeU9mT3JVVlFJb2JkdGtBb3cKLS0tIDdZdDNxOCtIYVNhY01mb1I2c1J2
            cGJPSkcrb1QvZHg4RVBIZi9xQzRmVUUKq01QKfW8VbOK/eEioe/4o5K2fi2KQHNO
            idWjG5ixMmUBzo4UC2IOxsqNALnVwl5SYBTzqjSGnTvVxfgWKxYUow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-30T19:53:03Z"
    mac: ENC[AES256_GCM,data:iNIQpuksG7kDb4W5ejpatGHntr52OF/QPkCgaqjey3C+WVgJQAjmMJmqpP2OKKVF8RdTHLBuz4sbn6oKALFqJZlll7G+aHv8z+YKrtcpHoL/H9bER+5z7o1yJ6qfzF11Qfic2na1254Am91RVcQGyH9GK8aHXZDRD32//k7w3Bo=,iv:C97AtcOAxQValrc0LaL1DVI1IfJOqzdQIAyImeb9XWg=,tag:gQo5m+7r4JtM/EYdKWHS1Q==,type:str]
    encrypted_regex: ^(name|ip|username|owner|repository|ips|node|cores|memory|disk_size|gateway|subnet|dns)$
    version: 3.10.2
