# Talos Kubernetes cluster configuration
# Centralized source of truth for both Terraform and Talos scripts
# Physical host management
physicalHosts:
    - name: ENC[AES256_GCM,data:Rypo4b/hzIm+Ce+rivI=,iv:fi9iYZU9fI+DnKTP5l9iNltaUV0WOmIhkMEfs05MKj0=,tag:eERO1Yw/zTRNjGH1zLn0tw==,type:str]
      username: ENC[AES256_GCM,data:vQJj6lY=,iv:E6ejUElxezsFWAlEe2wmcTmGgfhoD/bB93Yz31ClTu8=,tag:/dKcDhPN8FUhAlCwtqxfjw==,type:str]
      ip: ENC[AES256_GCM,data:h08UtyChJQyMrtBdAQ==,iv:ISg0ELzCa8ubZRfBcSi2DLGlJvk5tonptldRrP89OKA=,tag:5tZrGPdwTOX3SjMECO6F/w==,type:str]
    - name: ENC[AES256_GCM,data:QR2UhfalOndsb3K1,iv:AO+sw+lS0S5XLeuwEIVcY/UNhVBIB25wgLRxQegR/Go=,tag:NuMJSqiTVkGoqe45EXYMsg==,type:str]
      username: ENC[AES256_GCM,data:hePSUZ+dX7nm2ymf,iv:PZ/pX9pRsn49sk7Adr4Y4TU2UvGJS2CjasZCYoeoTGE=,tag:BB4RrTJEABw9GX6+7Xr9WQ==,type:str]
      ip: ENC[AES256_GCM,data:4pwBx/8rKFbgqMKSWw==,iv:42TkX2QWkjkEz5sVF/VjrC717+1vUtmDLUoxDywq1kI=,tag:bFTgMVsutFmpAxwNwLl2uw==,type:str]
    - name: ENC[AES256_GCM,data:+UJaHLAqBafue52s,iv:IZXyfTRk7QUFMOu8XoDC/FWP4iR2yGc1twNnTreWgwY=,tag:73WPDR4F8B526Rl2spq61g==,type:str]
      username: ENC[AES256_GCM,data:+YPlN2Tv1I9sByyh,iv:olsg4IsPJB75AFc9DGLYdFnqA/r47WJvCraw5Z2xzqA=,tag:SCCDZGAaqLiUPg5Ed7vZDA==,type:str]
      ip: ENC[AES256_GCM,data:xAYcUv6wf6InthlKCQ==,iv:miOe0XVd5ZtvfPBmppeLhtXJXRcR99snH3gM19W8A3A=,tag:lFjijtTUb4o7JvT1qm4Y5Q==,type:str]
    - name: ENC[AES256_GCM,data:GxEcX0+4EIBXcg==,iv:8N6FiTlEE1ZVh8oeCxjxmUYUJzmBc8enFGxYCU8zV5s=,tag:KXqPTyF/vOUG3iFBtOpVIg==,type:str]
      username: ENC[AES256_GCM,data:hJfuFfOutIx5Kg==,iv:Hbp8XHMPEIbn2Y0prHL2UVHcwdQ8PdnlAnADqJUBw2w=,tag:9afeXe3tye7KEfiFGPJU/g==,type:str]
      ip: ENC[AES256_GCM,data:Ry1YZulBc0Yc8AMxlA==,iv:eFN183bdxV9uXBj8SfyDCotGqb2Dxr9aWlfkkGwUR0Q=,tag:5owd9Pi06YTOITThr8RpPQ==,type:str]
# Cluster metadata
clusterName: ENC[AES256_GCM,data:O0qID0j1GNwOTUZRKjy4NOQ=,iv:/qIs4qq/Wlm08Ml/kCk9GT38gN6hYB/g4Ce5cOAX1w8=,tag:C1olgPKcVsJ4IPLR/st8Dg==,type:str]
# Can be 'staging' or 'production'
environment: staging
gitRepo:
    owner: ENC[AES256_GCM,data:vkay3piSTwWBlN5m,iv:r/yXoDO2r8qL0M/CVFdmgWSAxd8wIzSvoG6xvElAfdw=,tag:x8ljvKMGx6j29YWWOaZqAg==,type:str]
    repository: ENC[AES256_GCM,data:2t9We60gUQ==,iv:W2/fv/fnnBHU9R7MShAgKTObpRkkNSL271OjgCeMHkc=,tag:hatAFT64XcvwLe/gbvskfg==,type:str]
installIsoPath: ENC[AES256_GCM,data:C3cox7wfpn0cUTv7LmilYVDldNCQij/rbeZk,iv:sMNLVcHEfr8SH48H9J0EcpZffLW1pC/w5V+gsFNs4Hk=,tag:Qt3UdeTfeCk1PWbeVm8bXQ==,type:str]
# Control plane configuration
controlPlanes:
    count: 3
    ips:
        - ENC[AES256_GCM,data:v4lWlaV41ShvRp9mjg==,iv:6lgjLy6KwmfxEjQ/mSfD595W/+JpsJ4IujUgGKNU88g=,tag:sNfhHUeu7sM0PgMoLibaUQ==,type:str]
        - ENC[AES256_GCM,data:CZRTctfLU+24zYFTqg==,iv:ZN+WehsPpji92jHXfkXTlFjaKzqJIjyeUdCXeGLPH9k=,tag:V603fH7MPpfGYxAbq2an6w==,type:str]
        - ENC[AES256_GCM,data:7/yhV4m/kTI0y5QNHA==,iv:o0KKA6fU0yMuHAiIjPC9V30MIF3rUafqu3B2PSmyeF4=,tag:ZCDRPfbOKY3z1+NUCZQMOQ==,type:str]
    # Maps to the index in ips array
    profiles:
        # Primary
        - node: ENC[AES256_GCM,data:4x1CmlTxSegayGld,iv:Qo+q6D6O9cqWFNB+xAbtFjOWuBrRnu9zkS2CJBRJ/7M=,tag:q+sk56ydnr33DhrFcV5fxg==,type:str]
          cores: ENC[AES256_GCM,data:9Q==,iv:NGQa94mQPO7NoaisGWSqKQLd4kHCgYBnYpzxxSvHSbc=,tag:jl8iJNSv8F0f1tg3ktoNdg==,type:int]
          memory: ENC[AES256_GCM,data:58nDUw==,iv:Z95aWSlOKX3IyNJc/p1KiFIVt2VzGzb5vyEPJSrSjRk=,tag:EZjyFVrt+l2DgXz+excR5w==,type:int]
          disk_size: ENC[AES256_GCM,data:6Gft,iv:7E29KfkWEcEuOPvgV8lM9OJq7dvQILqb+J7BpVJW15o=,tag:5Q41XwXcYdVvcWBCJwxDmg==,type:str]
        # Secondary
        - node: ENC[AES256_GCM,data:y+Z45FVh01rNNu/l,iv:VcW52cB0CEKVRqHvAl8EC70fgniX6Ytu7+I53um9ZHQ=,tag:rUjMIkoF1DVU+wGJByp2mg==,type:str]
          cores: ENC[AES256_GCM,data:fQ==,iv:GAJW2OzoO9QHAkb9LBGu4F6yvpDpLoEWQSuHpgHQS1w=,tag:lUqnIZrL2gfhvrDFgzb0wA==,type:int]
          memory: ENC[AES256_GCM,data:pytgYQ==,iv:LfnlRWvwUg2oWF2xXZgIQfrgPDfIFIQffBPEG6MbmJ0=,tag:msABXj5suMRv2Z+wt4tm/w==,type:int]
          disk_size: ENC[AES256_GCM,data:yxjp,iv:FYVKFLHxfgDQBt2bqpRmRccpAlgCLjvJRBT0WMYzbdE=,tag:eI1TsjL2tHBVaUZxIFeZ+A==,type:str]
        # Tertiary
        - node: ENC[AES256_GCM,data:2iATlGQJTKj6PU6PWkk=,iv:qlxEbRzWIxo7cHhA39Dj0Gpi++ObLVb6sgyBal1+5Kw=,tag:ti7qFiFjUBAyCx2uwRudcg==,type:str]
          cores: ENC[AES256_GCM,data:TQ==,iv:fa+8IGkrw9zOcyzdws4LJhJRIoNfTpTAYuUqhLiLFPo=,tag:jQYv2m2oC3PJ/Ac4ggNt/w==,type:int]
          memory: ENC[AES256_GCM,data:nqciNQ==,iv:PwDUXxsiXaZQo3ZZwLm7BmO8EhGgI9G+odlD6qbwwng=,tag:tsX7gGCfb1tTHTqtSGVxGA==,type:int]
          disk_size: ENC[AES256_GCM,data:FFoR,iv:yLGb6K6xQhml2biVj6QxkJmyVofs5anVrlD9iMTGhqY=,tag:nADdn0K1por20aaYmIONCg==,type:str]
# Worker node configuration
workers:
    count: 4
    ips:
        - ENC[AES256_GCM,data:MPQRNJ237VqOBZ5KGA==,iv:5DPFFBqaRlYVs53AQ/yMhMvLRsYjSrGiKCAMelSe0iU=,tag:dKt4ay/Gadvyuqw9SjkitA==,type:str]
        - ENC[AES256_GCM,data:oLqIf0SsLSKTlA0l4Q==,iv:JXqDJC5vaxxVvq6cghC0u+iSLsuSyzLlJKi5vvYetBA=,tag:2osXQ+T2ohfmI2xRTAn+Ig==,type:str]
        - ENC[AES256_GCM,data:mibj6thxHROMIc4JKA==,iv:Xu7fT6gxjcbSKah06PiyCRjBYdgJ8LeKH5hD3dHLSZ4=,tag:dJrThvx0uNe1qlHhe6XZqQ==,type:str]
        - ENC[AES256_GCM,data:/EYyYABUbXy2QtOgCw==,iv:0z5fWHgeEIp0ZKQpKzH5lufjBIBs5Mnd5In6AG/JP3M=,tag:Bt5eiBqIteFzqzgsbuIIFw==,type:str]
    # Maps to the index in ips array
    profiles:
        # Worker 1
        - node: ENC[AES256_GCM,data:DYTt0M+VX4tjWpx9,iv:/2VgFsQU1trwyAS+pUOWR6mYjj5cEZHtUAwKXb0KHJE=,tag:Mgm0K7KudhrNgSiP9LXsMQ==,type:str]
          cores: ENC[AES256_GCM,data:PA==,iv:Bx49CEHq/LiOYM+nxwS1c9ThjberLBntPVdS6UYIdG0=,tag:e1hgWVIZSa/PkzkGA27oGA==,type:int]
          memory: ENC[AES256_GCM,data:zwdEDg==,iv:qgRkJW0ug3gdsEc3n5TEpG9am5aLnAW80Uwd+2uo7+c=,tag:Eqx2/cv18lq0nhL6d0s/kg==,type:int]
          disk_size: ENC[AES256_GCM,data:wadM,iv:dpFBYa/+zQM0KtIy7MIUVys2ZCWlwKQTKcN28TjqhWY=,tag:PWz6C6EhEupDNR9LlOjiuw==,type:str]
        # Worker 2
        - node: ENC[AES256_GCM,data:O+EjgavgSGcLCP/x,iv:n3Iq0uYIv974Jhdmm3azE38MoS8cRaiECGhQOZoJ/Lg=,tag:W2iWttCzPbCDW42UBmP6EQ==,type:str]
          cores: ENC[AES256_GCM,data:nA==,iv:Jr9NWyQDIMP92coK3evsWTVFZDP5h/GNq9aS7uyN+KQ=,tag:M8UHb6sk44zzzxfpwlDUhw==,type:int]
          memory: ENC[AES256_GCM,data:NWdvwg==,iv:I9tNKxfdZNmBYVVO1ZvxDqERK9mBxWPI5yAYmsobsR4=,tag:ywUOXeEhyaznvfAVnOJ6bg==,type:int]
          disk_size: ENC[AES256_GCM,data:s/c2,iv:elqvF/Fq0aH8Kd07PEVPggAVeLtR/7v0aXdxZkOmbJI=,tag:xqqzEK43zt7ODZMUfSQerA==,type:str]
        # Worker 3
        - node: ENC[AES256_GCM,data:gQpaxQCRZfvXhYuj,iv:WEGzv82HJKmQBzf2PZqFiKCeTdGzJ508gd9PV3WVXfk=,tag:x+zf25f70E8iNWwZ4iUaXw==,type:str]
          cores: ENC[AES256_GCM,data:zQ==,iv:liYMKADKBeTtE8gFQlsrvhU3ol2c2kSzEaBiwHl2nG8=,tag:wLEehOS5Z0+7LU3v3pboCQ==,type:int]
          memory: ENC[AES256_GCM,data:ykrT4g==,iv:ou/VQDggqyWgpA/79kjHV4cNY6qMuOXaTMzeaSUVing=,tag:G7VmjXiVK4UcbFCYA2Uwdw==,type:int]
          disk_size: ENC[AES256_GCM,data:/Vzi,iv:YZdCi9CyqpDdiEWib29x5DinSpSwciaMmHccEIa9mQQ=,tag:vChkGI0Y4jGM9nCXg32aQQ==,type:str]
        # Worker 4
        - node: ENC[AES256_GCM,data:7S60UYAVQqoB3Q==,iv:4e356LzU1w1x46nM3F4mvj5jFWBl7qIirTqrf1dzJgU=,tag:FFxBgx93M++Rx9d6weKt6g==,type:str]
          cores: ENC[AES256_GCM,data:tg==,iv:JY/62x0azl25ROIFgQShbZJkP5KdrxkX1UZgnPRewfI=,tag:zePY1jY+kI1tHNvYzeFbKA==,type:int]
          memory: ENC[AES256_GCM,data:F4Ew9A==,iv:JmMdD9QenlJfjLQI/0W87vPivwN0SBbnbgBVtlXJdnk=,tag:6e7LfGJGQTpKP7SNjdTsYA==,type:int]
          disk_size: ENC[AES256_GCM,data:OFFw,iv:ZMawKpG7RbP1FsHEjhoa1BMUubazgeZgQQ0GnuuXTv4=,tag:GrNjtIT5UaVCVZeNGfzC/g==,type:str]
# Network configuration
network:
    gateway: ENC[AES256_GCM,data:PJ+kiyZkw5rb9xs=,iv:gFipvYUlvQzjP4BgT/aG9C4SEUk+EaPkVkmQPdbkQVc=,tag:Ta8zJ7tQzlB1Q8av5kTqaw==,type:str]
    subnet: ENC[AES256_GCM,data:90joqPm9X9CQDzVN/gA=,iv:eeapxXyz2+gtYjpgY0E68ka/GO+T15B1ofPBz/KrGHw=,tag:Lf4sLa5SvwV44pbnA68X/w==,type:str]
    dns:
        - ENC[AES256_GCM,data:MYeV7FF6KGmD1qU=,iv:a8RH7M07tSsmzJAB/jPch8hQ+88mxaXxWrKg7yYlS8g=,tag:g5W7wHSVtA82IA/WDNr0dA==,type:str]
        - ENC[AES256_GCM,data:F8JaCswdyQ==,iv:i5MMUsojMV9SfjP2a1xDr7+/bb48ErdjqlZy/cy9ywg=,tag:W5R5ply9W3pcEuioKAFHJw==,type:str]
# Storage configuration
storage:
    # NFS path for ISOs in Proxmox
    isoPath: iso-nfs:iso
    # Storage location for VM disks
    vmDiskStorage: local
sops:
    age:
        - recipient: age1wgsnca8gljfz2659cs8rmme7aanwznkdakck32qmeks7sslec50svgdjwv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSWNEcDZSK1RaVUNacklw
            ZVRPalZEQmtvNTh5bGZndXNmT0Q4QWVSWkNVCnhuVDBwR29wVXNYbFcyZUppM0t0
            SVZiSDhORW4zZ0J0VzdqQi8zQlZKaEEKLS0tIGlLWmJkUUxqd2tzcWp0aFJOVTZU
            aEpEbEQ3ME5wTmlma09kaGt1aXAyUHMKu58Vuk71EXadV4HLblB2xiOy6t6F9qPM
            fuk7c5vDznxXWQnIlUj79NtFYmsKVV0qnKQZcuxFQGZFtyw22RIJUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-06T12:49:25Z"
    mac: ENC[AES256_GCM,data:4AkI7Md0ArXmTHLEcRzzFscka4cALR9A14vpTB4429VvfPpcocPyLZdE3eUMoDI2O3oI4M1FaXJ4nEOTY9BPqIq8UIPZ3p7qnflT6Cj2o7Blk5Z3f2K/WVrL7a1e6akWAK8thg/Tl8O838bdf+gyZ7R8Cmd4TFS8pgK8wb90iLU=,iv:Z2CbaUPkqFFQ6dqLcubuZz6CkncIZRGZakrAsIWP0nw=,tag:kJrbxq/W9RDL+SPsCNJezQ==,type:str]
    encrypted_regex: ^(name|ip|username|owner|installIsoPath|clusterName|talosVersion|repository|ips|node|cores|memory|disk_size|gateway|subnet|dns)$
    version: 3.10.2
