# Talos Kubernetes cluster configuration
# Centralized source of truth for both Terraform and Talos scripts
# Physical host management
physicalHosts:
    - name: ENC[AES256_GCM,data:/SOcryVRWg1EV8OsLtc=,iv:EYrEmL5LLRKph+rJnTAIb5sRkNpKHRZSD4LW25C0zp8=,tag:GzuA/lMa6lp+jRi/EOQZ7A==,type:str]
      username: ENC[AES256_GCM,data:xEqamBI=,iv:6nLSCYf+amk2jpmsxhSjSrLRlqdxy+tOwV6J6qvgMl4=,tag:/YjzmjmdUVbAJuno2SOvCA==,type:str]
      ip: ENC[AES256_GCM,data:rNVaVFSvVv5xjqxr9Q==,iv:inuRVtky22QizaV0F1E6vn2ZTaTPuzrjeiaB4sdMa4c=,tag:earF+0RB4TTw+iHIBt6j4Q==,type:str]
    - name: ENC[AES256_GCM,data:ZYHnU11PMNxnIla5,iv:UWHmBlt8U14Cp9W61bC0+auYHZstTUocA+74mzMQ81g=,tag:9isrQtsA4zg9s4GkfsYcBA==,type:str]
      username: ENC[AES256_GCM,data:BCi2OBQ4obtcrgHC,iv:g/sO8YRcwqX44N1vgFQAQgL4dal73/OFw+M1cL3IEHU=,tag:G/FcMwEktffikVcH9Muj6w==,type:str]
      ip: ENC[AES256_GCM,data:R3h7vCsMljhXuw0XBQ==,iv:if/RfwAi7/CaMxm6Z3f3yOpPzsugmMOpyAcu1h1L0/0=,tag:oVfPkyyqVa4fVGCjDilGNg==,type:str]
    - name: ENC[AES256_GCM,data:4xV8grxDiWx4Suoh,iv:DcdTSWxk2jpCe1K3LZd2fcY5O3pG4UtpoHqNMEp1KRA=,tag:mq7FdmAUwO8D7i1JBJa37g==,type:str]
      username: ENC[AES256_GCM,data:z5jtv/p25BUWOfsP,iv:F279abU45nXO/HgSlkojJg6UbSeuGLA4sHF2fNDCslQ=,tag:ir5SlP7SqXW5UTsxp98oLg==,type:str]
      ip: ENC[AES256_GCM,data:x8r73oYB7oVcy3ImOQ==,iv:SxT4G5a/M9q7ntXH/yP5WlRIuwMQfdff4Is0GGklgWo=,tag:t6tGlaKjRZZ2QlvjOyhHdg==,type:str]
    - name: ENC[AES256_GCM,data:iX5ENixgNvwXhQ==,iv:Wicn+8sE0MFOY4YWQXnxOwE4dX9sLdGNvL13t1UH6NY=,tag:s4Jx3cyBYoLAPBJR/N6UBg==,type:str]
      username: ENC[AES256_GCM,data:AjT4AHiVqSKLQg==,iv:pAZVuAa4NJb5Td60achn/j4rCM39xqLxVerYexo7vvM=,tag:i8lAmFNjCfshdfzJU1RKzQ==,type:str]
      ip: ENC[AES256_GCM,data:77Zf5quCWneKyGsIeg==,iv:/Pnxw5MTREn7k7W5DElpgMLc7FYQkIbUpeTr12Da+c0=,tag:nGyvsgYRWpjEqofr+N7B6Q==,type:str]
# Cluster metadata
clusterName: talos-k8s-cluster
# Can be 'staging' or 'production'
environment: staging
gitRepo:
    owner: ENC[AES256_GCM,data:XCpBDybPTJzKr9kP,iv:jWTV+PoWGBcGDov3DRjZuB2kRFMfZ5CfVI2uNTPneU8=,tag:iqjzItQM+SYzqFeEY1ZgXQ==,type:str]
    repository: ENC[AES256_GCM,data:Oa0Ri3bFrQ==,iv:TOvfP+ky4zM55au6gQUqKtGOZeefv5AIYojvK0p9fHQ=,tag:W3L/5hIRJQVFqI7uzCAsjA==,type:str]
# Control plane configuration
controlPlanes:
    count: 3
    ips:
        - ENC[AES256_GCM,data:pyJ6K+AhfVfXQ7MmqQ==,iv:s2g3/qt3vY9AQwSB1U3HzKs1J7IYpdhYGxcjwrGizvY=,tag:PfktbX01PlMEk+fg2rh5mQ==,type:str]
        - ENC[AES256_GCM,data:w0rkiE58lF+p/4MK8A==,iv:ayPxcouLHrx4g2Do7bHdLfeVOY+utEDmeOHiPIENgAU=,tag:34oLkN00GCbP2RbxHncCWw==,type:str]
        - ENC[AES256_GCM,data:+Zfh47008a3Zg+a4ug==,iv:zuaAV+Shob3LB3VkTi3NfE59HzeI9gmf9173bezVdgs=,tag:3BrYlTO71cTb8MBRdMIyqg==,type:str]
    # Maps to the index in ips array
    profiles:
        # Primary
        - node: ENC[AES256_GCM,data:njBSy2j1TD9uKKZj,iv:N11a68omMJipsrFm89Kq38m0fj9aw5sFaGJ5H05d5Fw=,tag:GPQG0EOMP9jX+rFE4tFIYg==,type:str]
          cores: ENC[AES256_GCM,data:ew==,iv:+OOX1ph3TspkdNR3nKLgcPk1OvYhwd7rfELC1ZfM/Ng=,tag:H5i048ERS5TG/DcbYxoHpg==,type:int]
          memory: ENC[AES256_GCM,data:VGMKhA==,iv:5rSYu0pI7yZ6JH8nQN6zErwie/Xqv4SAqZZkqHNSWmg=,tag:aa7MqnnjEHrZJQeOuokXbw==,type:int]
          disk_size: ENC[AES256_GCM,data:MkRG,iv:mL8F2lfSPwjGV2zwYnhA0TPYpdWi95+ZQgdHRNG/hhs=,tag:UNymP1pPT1q5Ye8s6rnCRQ==,type:str]
        # Secondary
        - node: ENC[AES256_GCM,data:pdrsqXgIk2RmkdrS,iv:lDClQJmDzS7bp4pB1PH4l730cxEeKqvFHnXUHv937Eo=,tag:2uSzicSeruvmYSCQqNpB3Q==,type:str]
          cores: ENC[AES256_GCM,data:4Q==,iv:JvLDwq815Ocy8MmU5l63HfDSeSghU87n+OrDL6q27CI=,tag:H8lLE7Wrbv6vCdMTOCOEIQ==,type:int]
          memory: ENC[AES256_GCM,data:XydNDQ==,iv:kBdfz1DazJuyZiEoKagkq6N3vbXKbIjv5Y+CjQnqCj4=,tag:C+sXlkdFEj2qMCtbsk+/dA==,type:int]
          disk_size: ENC[AES256_GCM,data:kzNK,iv:r3OVBqhcELf+PRrPmyTwJWrwdWU55JVIHjqBFDFvd0w=,tag:po39Z1c+G0NUkl+isBXCSg==,type:str]
        # Tertiary
        - node: ENC[AES256_GCM,data:wOe3Gs8uULvBjHMFJJk=,iv:JMu0u2GIcy/GesHP2L56KEPsIhBlkF9jxZ/rc+ZOs0c=,tag:ouAs8n2LA00s2A7wgT+fOg==,type:str]
          cores: ENC[AES256_GCM,data:aw==,iv:nslXm5GdVZpdVA1OXlyA4Hp3uZ2A9KzzRjm/QRnlNtc=,tag:bebLz5fQ4QXMzQwwX2MfZQ==,type:int]
          memory: ENC[AES256_GCM,data:7Lh24w==,iv:UKhkRZ4SrFqsUi9Z/2LkkB5J0bGPtTmOp+UkuCcCAno=,tag:x8TDX7lhdm4dlgIYOdV7EA==,type:int]
          disk_size: ENC[AES256_GCM,data:fbVe,iv:KNeMPrqi1H+ZlKMxPflE7E1CQSOOR7XTxVpJVEAkaeU=,tag:rzOW4LnicplrJduqZp5SdQ==,type:str]
# Worker node configuration
workers:
    count: 4
    ips:
        - ENC[AES256_GCM,data:8zWIOHmAmOhlFRmqGw==,iv:2FM+nPw+gTDSZMbF/e4I0TDJhi2uNCNlvtdA8NeX9p4=,tag:JrAxoQxIS0hbHCtRu8Z5iQ==,type:str]
        - ENC[AES256_GCM,data:umQ+k+sqPNbsc7b3Jw==,iv:T1udtuVLvBz5ZX0srabzMR+uVmyePA5flHK3pc2hs8s=,tag:D/trtYE0wQ19T9fUoVQrEg==,type:str]
        - ENC[AES256_GCM,data:HxCLINED3ig6jPZ3TA==,iv:Hokm9L56VPc2HyOINRKjb7KX5CZy/qpYElTgPL6QXsc=,tag:TmmM1uvcZDJW/SIj0Zp6ag==,type:str]
        - ENC[AES256_GCM,data:CbHxPyE3u4EyZqFXOA==,iv:v7+UdXUDsVcTTZJOraxSRrzWN/XwWoUZ5u6NCVWJTnA=,tag:+qaf3ooBVnxG9Ylpopv/Fw==,type:str]
    # Maps to the index in ips array
    profiles:
        # Worker 1
        - node: ENC[AES256_GCM,data:/D0MewczQOYd6d6Y,iv:MBjWlYRxRRnnFbPcc3FTJeJaVBW3YG6G8rzinQwJldI=,tag:qTGpHlA/6OvZFMniKnrZ5g==,type:str]
          cores: ENC[AES256_GCM,data:kw==,iv:bRjz/4ecbTGhJeU2SJdclrveFUjAMgY6J6psBT5DdsY=,tag:6kJXIb5TlnEEkKWLjXgVmQ==,type:int]
          memory: ENC[AES256_GCM,data:HlAYIw==,iv:tYhp5VmejTsUHrbo/27xvdfySoDbSzkhlWoi8rOV4QY=,tag:cmreQCa/d4iTjcHKfgpYkg==,type:int]
          disk_size: ENC[AES256_GCM,data:ivGM,iv:BUuHV1LavGzv/Nz99twTGScOESBjmOfZFJQBAul+imc=,tag:SknYwmObPj0VnXHv5aCSBg==,type:str]
        # Worker 2
        - node: ENC[AES256_GCM,data:9czHz8Q1To78MrOK,iv:0fWba/7Z6GpTV5c/de3mcGfqcbjuvcV3hZm1hiUb4n4=,tag:2M62sxVQqTMyuWV0g+Ypug==,type:str]
          cores: ENC[AES256_GCM,data:+g==,iv:KhslcVjfqbjUZgu3NfUjPwX7/2qW1PnpiPPXRE2CnMs=,tag:HvEpZIMlpT2wOEd62eqKxw==,type:int]
          memory: ENC[AES256_GCM,data:BVXsfg==,iv:IWIZ74gdxjSPJZm03aZ7WTXDGEwPiJ7/c6h7uLdQorc=,tag:3aijbgpC6srZLmiSFuiCyA==,type:int]
          disk_size: ENC[AES256_GCM,data:3pie,iv:aCT63GuoIJLHhno/NHbxzLNT4qhOiKRsfcOoGfHFKnc=,tag:PsRSSRVc5uYEKdQ0WEfsMg==,type:str]
        # Worker 3
        - node: ENC[AES256_GCM,data:eDfKYJSqR7B8fFwg,iv:KAmiF2CvtQ2mePU/YRQpbfroYo2HB21JNAlo+UVcsJI=,tag:ufiz6BgdsFisgR9KSs/pCQ==,type:str]
          cores: ENC[AES256_GCM,data:9w==,iv:yuqEWUjyKLMDs6yg3kGPugYJ8n7EZMSMyne02BWewG0=,tag:jtl0Elj3ENXlC8CmujHe1g==,type:int]
          memory: ENC[AES256_GCM,data:2g4YFQ==,iv:sOschYcZwmkNNqIAdCQQFaE3d5DFq6PX2LZsm9WjGu4=,tag:KZ4JDvt2CnXSde8svxqg/Q==,type:int]
          disk_size: ENC[AES256_GCM,data:rhBu,iv:pnLYZl65v//cm/cgD02flkv4gAvEIJjUdrUFXlo1etY=,tag:THMwuv8+H+c+9YKXgHS0nA==,type:str]
        # Worker 4
        - node: ENC[AES256_GCM,data:eI9oyTE3903vlg==,iv:qLJczKNbTwOCeIrtO7LMDD5/sTbsjqnIOduRDviu1Q8=,tag:jTM2CqcR7ZDpEwg/g+KDGQ==,type:str]
          cores: ENC[AES256_GCM,data:LQ==,iv:RvnAyQHP5CRn1cz4Kdx3J4yrdJ6t2TNl8PZLUo9ZlBs=,tag:sCvX8Diydh8y2UJSOH9YQg==,type:int]
          memory: ENC[AES256_GCM,data:I0nnSw==,iv:A3b2tG7P06dAmNYk3TI3zpv/PvWEj+ZKdVQlv345yzA=,tag:z7XKmh+3LJk7L4TFHSihfQ==,type:int]
          disk_size: ENC[AES256_GCM,data:IdIk,iv:Xp2CCBkNTc8369/jLClN1yXs2E6QsxqJJF4MjyEHoPs=,tag:CpRRzSYcI/5DJRhusDXlng==,type:str]
# Network configuration
network:
    gateway: ENC[AES256_GCM,data:yZ1O1Ljf6CAtAik=,iv:OxmY5VVFY2s6o7RoKoLSLsTzCX9dD721Q9LWpYX0uJo=,tag:HWrqRrsumW7n5oqnMvg4ww==,type:str]
    subnet: ENC[AES256_GCM,data:lQmH54pCNgQEOnE0T7M=,iv:kC+xAYsIG07pbiffpk8KIowBBTXDknhQCs2vOia9/kY=,tag:E4GvL6vHpNeFy8dtcmRDKQ==,type:str]
    dns:
        - ENC[AES256_GCM,data:BAkJYxw1QXhgTpk=,iv:ttB/noUKz9/ugsB+3OOgIuw2efzMPfxvBuVY8TQPKHw=,tag:M342FLB0U7WVhOAEAmx5cg==,type:str]
        - ENC[AES256_GCM,data:8gpoTvtABA==,iv:Tw8QnxIQddt8Z3BorgNwOkgDbvVBQOF6tCqGQskQjVg=,tag:JpuZ0nJ/4WYmF5heYSEKOw==,type:str]
# Storage configuration
storage:
    # NFS path for ISOs in Proxmox
    isoPath: iso-nfs:iso
    # Storage location for VM disks
    vmDiskStorage: local
sops:
    age:
        - recipient: age1wgsnca8gljfz2659cs8rmme7aanwznkdakck32qmeks7sslec50svgdjwv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaYnpqWmtCNW9WNlJhUnQ5
            YkNiYXExWStzT1p2THZVVjB6R1gvZkI5N2hFCjEyVm10elNQWk9iSWpwaWpuck8r
            bzVvNGNuenozcEJpNXZUZWFQWERLcWMKLS0tIGhaQ3JpamtRR1NyUXg0NVh4ZGpX
            UUh3ak96VjRPcnRtZXdhcURzNkJvUEEKN0FL0SI59rgL4NbKI69r65m6zAU1iMtY
            syDvred8GTMM8vrBzCC2/+NDjDYll46jGiO9FAix7+3ebIzTQswP7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-02T16:05:58Z"
    mac: ENC[AES256_GCM,data:czppkm9/pv/vNYLoZLummnoMpr4OrIiVHFweZDX3UHt9eVC5beALwAirQmwvHT8SzStJDjcbL1fjZ2SiWGwAjPlLyHfaccGhAV6K9Zb1OObL1CTyrT+qSKu8cBkdpK34rqN2YAWAKlS6sARTuLkBlgarO/Z5QOh44VUSukjiQ+U=,iv:cyxUhWPLD309v6PXYkIHOl43GKAEnccs6+pshzAD//c=,tag:GBU4ms+VGnKg5gNG3d8D4g==,type:str]
    encrypted_regex: ^(name|ip|username|owner|repository|ips|node|cores|memory|disk_size|gateway|subnet|dns)$
    version: 3.10.2
