apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "66.2.2"
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: monitoring
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
    ignore:
      # Ignore "validated" annotation, which is not inserted during install
      - paths: ["/metadata/annotations/prometheus-operator-validated"]
        target:
          kind: PrometheusRule
  values:
    grafana:
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - host: monitoring.niels-fechtel.com
        path: /
          pathType: Prefix
          backend:
            service:
              name: prometheus-stack-grafana
              port:
                number: 80
  valuesFrom:
    - kind: Secret
      name: kube-prometheus-values
      valuesKey: grafanaAdminPassword
      targetPath: grafana.adminPassword


