apiVersion: v1
data:
    CLOUDINARY_API_KEY: ENC[AES256_GCM,data:KuHyMU9uhB/UcU4AjW2XPgSxT3I=,iv:5C/6aT+1bPXtMpjBkbv5yfl/wNF74LIEXBT0wDd3z3g=,tag:ADaRbYWNRqFBcdJ8FNwI8Q==,type:str]
    CLOUDINARY_API_SECRET: ENC[AES256_GCM,data:cYyrJR/928nX2O96agVStFsGvRD8KxOnZWAmGvd3/8DrtwDu,iv:HvUjVaxdvN8Cxcu7ef0aIosRz+72T2Ipp+xTqJcb3Nw=,tag:69AFB3LbtNOKn9rTC1dWsg==,type:str]
    CLOUDINARY_NAME: ENC[AES256_GCM,data:o1IsaWbHxfjT8aLLC1EIhYLEA/RT8zQD,iv:dsuEo3CpZgcPqTM7tQ9KooEhNHkAQGRt3BAFrdAoYB8=,tag:MoNJ5HilMSj3Km3OksXOvA==,type:str]
    DB_CONNECTION_URL: ENC[AES256_GCM,data:WHhsnFlD9aBc9b8+YcwqeFHIkmtFX0eslds4bqQb2OcvgSeKClHpLJ/Cyq2tLcsDyduDFJ0fa4GQzdqJgd7vdG5P0XYem2UY5QnLMT9iPfzX0gE1LYnCzIHynUuOdCS01Uu2hz244OZwnv22Uu8luUMDRs8J02M+HQz0RXUNUit00g4NXM3qvduT7vqADfOXQHfMnsw1XNwadEhLjqKjYg/pgiqc20+DOM3lLgZGcbr6pWUtIqQMLR3SD22nkeLuXle6lQ==,iv:W4+X2EsdFdQ80GXeArpgmeJVr9dq+nQmwXtcYm7hWqs=,tag:k8a7rwsAxro600jM0B232Q==,type:str]
    HELLO_EMAIL_ADDRESS: ENC[AES256_GCM,data:PfKDOK/YmeQKDkaKVZhIlUTpOPOFQMB5QETbiUxbOJalZo3i9qnRVKtYXNU=,iv:eW0lvyx1WxHL25zEaLncv7G+Z15/tcs40FKnxlpsTIU=,tag:FsM+Af4TsrD8nplzGasBqw==,type:str]
    JWT_KEY: ENC[AES256_GCM,data:Za6HTuxV5eENvkqDbeRLXtnBNHENfjXOhH1VFfqZbX6sjriCO0zBciuYyzOZUD3xau93HlziNTcM2+oX/b/QrKods/FMslwkXhNiTbsbzV42j55Vk7yrQN1i5b+/T4ITBA5Xr2iXly8FlnS9wHY1gsZZ+TX1it87jRFFwmt5wn+jFtsAJ4L/RM5iDu5w3NDLEVXQoCq475Y=,iv:az2xe1x5yEv4sztXhe0xjMC2w0R5/+7VHOqLHdzawhc=,tag:3xcvSUlfCD2+Ptt6eCn/XA==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:Ff3EsCrQYi+WV3L5frY2qkHl8SPT3p8j1CKw6sK5HXmS798PhFvZLSvmA3wcnQFn5GpTw3MxuB1CvIZ66khQUMfS7DnLfqv7D8AOezeUqfZ4UJIxQmHyBWjstuzKD3ox6d3uTp+G06lI0sBjHZHdKpNUS7o3KiDgFKUoJb9kuDiugCMlEd0L4oRE/qAfYTMvEv+Zjl5Hj/teEjHTj1nPXLOp5Cxn4QLwwmdcy06r1mV/YKNaqVeqW/e4q9/eMaexUIuzi1IC4ssqcsCyGcZ5/VLjQhxALig6xswaGw==,iv:9RIfpodi8GVCmgqbfw8pk6BixIt7Ofihs9Xl2OlHKmg=,tag:JrliDrjg6LeNW9/ui5Pb8A==,type:str]
    PORT: ENC[AES256_GCM,data:7YtGCVVuWZA=,iv:xh1y0NoslfkWOQaQMivi0nD80mt8iatvG9OGL0l9PUc=,tag:6iFxHO7t1K+V1FmG79NBrg==,type:str]
    RESEND_API_KEY: ENC[AES256_GCM,data:Sg+TMh55g6do+jUfG5q7oxZY1abUIp5v6FNlnoDZ89qaAuvT+IQKeK8wyUzAeHMr,iv:awvGOARHVCIz9C64wuZOevXLsPyI1jJSG4X11TGGRPc=,tag:wMWW3dBg6HDw7Evr3R1fhw==,type:str]
    WEB_BASE_URL: ENC[AES256_GCM,data:A7xeJJzJAB+7qGnFQXlNCwJsMYLAEptP8HBV9hDt0tcTQ7Xz,iv:RrclRRdOp1GHx1qefrN2dshg98hn32tPw/xFqjp90QY=,tag:brFnLTquqo6GHCfMBgDUbA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: api-env
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wgsnca8gljfz2659cs8rmme7aanwznkdakck32qmeks7sslec50svgdjwv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBT0pkdGVJMkI4VlBkY3Jr
            bnQwNzcwTTlEVUQ5a0g0VlhzQ2dXdlNTUDNJClVmL0pRNUpMNXVGSE9uTzhkSVJJ
            Z2lBU2l1RGxUVjRvSWQwMDRyYnJiRUUKLS0tIGY5L24xRWdFWmFJeTBUSnJIWnI2
            TCsvZUg0eU9vLzBIWWMzTnI2KzBSVWMK3gN25DkfHh/otgeJHaGSBNj15ILR+qOL
            rWOAh44m58apZ5Awj8hwPw7OKLFg6KiAt34vsR/UZP9HZ2IF0OemVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-01T00:15:13Z"
    mac: ENC[AES256_GCM,data:OFmb8+nZetKP9Ocfph3hPkNpB0OgbfjK4dnPPoN/ydLBISLtvpstlBmZCAxLDg5rUbtfFECNeg67J9QJcoIlbTSHk7/MLsX0dW24ZaEAJAsfcFK6nMxNsL+/eHT2KLsfA0IVRTPX0JMWQWCc7RrazceWaBWSpw8tgbqMNX4uKhg=,iv:o/rPw68T2uPJ6k/GpBq7cEi9MjDmy0ulSSyRlm+qK9o=,tag:7yRoNW1kDx++XVhoY6nHuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
