apiVersion: v1
data:
    API_SERVER_URL: ENC[AES256_GCM,data:UVq2Q4ISAN6Q5P9GWuIMBiQEB+0Y91IW,iv:127L7dsIONVsd+srZIceUbArLD60h1p7cTs744Y8XFc=,tag:e3MoG0FUdmAb9uBgDWPU5A==,type:str]
    AUTH_GOOGLE_ID: ENC[AES256_GCM,data:U1d74wIc11jsD1G+w4Pc4mHJVcxMsfgzlS7ROvlMpQKlbB63bqj46ir4fZb41l6YxetJxuh7GcySU8PAmYLkQQNiQ/3yB+01+QSHeGylcJZF1U7Zajcl9UGdxbuu2EHJxjauvA==,iv:/pwWO9oOVBsMoCtHMq/xLQfutp3yxodvfMWs55nY+Ow=,tag:f37ZanXdAQuEfpXeow+T3Q==,type:str]
    AUTH_GOOGLE_SECRET: ENC[AES256_GCM,data:JHHYhDx8OY8Is9AY4/2hOoYBY0HzFzGJtHWHlRx/HkDrSnAL5pkvsUEMHWvIUxzxcmNDKA==,iv:z9JCiNFsmA8o4gTx431nPmZl6I1Z/jsl+lyH9qXIbfc=,tag:UOQs2uUNqMNN2Zf8rQuqQQ==,type:str]
    AUTH_SECRET: ENC[AES256_GCM,data:zGThjJrSditKjFWJ38xwX6a9/myTlilXMZvxWr14NsjbdqkngXEmkR/+PEAmQjarBr/uCJCRnybQXHHu2bMha6JQLe4mP8hX+oPhOqb7lC4gW1osVo3c6jHghN/ks4HNsN6N8Jo/eCMlUvckaDRnpxFgTiDLQSeW5Ytjh4V5jB02vNMulch1gJWTMRo=,iv:gWY8wq6RpWqnTIUZw93vxl/hX3ucwGZDTxA+womYhEA=,tag:87a53TDZePnnBgD/jeNAiQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: web-env
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wgsnca8gljfz2659cs8rmme7aanwznkdakck32qmeks7sslec50svgdjwv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVaG5HV3FZb3R2eWlHUElh
            aE5tejM3S2prVWlsNHlHbmt0VU9OcnZPaDJzCmdBbHExSlB5NXZqbUV2dmdxZm5u
            TUZ1RDRLKzZMOFhUSUlHeWNUQjJIdEUKLS0tIGh1aUxPRDd6c0Y0Zm9tWEl6OUhF
            L2FBbnE0TzlyeEhtUkRaVDdvMlVYMncKIfi4A3m5SahVgdN9+RGXuBhF7FzqyOQU
            UHwcdHge/OZYrN8AajMw2peNVDzNDukZwZb7rb7pWrlNybvHAbtsKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-28T12:04:31Z"
    mac: ENC[AES256_GCM,data:LsZev1CKG+d0HOyVAsD5L3/osKcAVDNkc+CysHXYkZUqDoxVmf1GpXhYq0nLwbEswZdnJz4lR8esiT0EZxafgou2OFPHeZCvFSUJ2KG5cvLRS4dJoriwUv5cU0R+hdlJrpH1PxnQR3elK0R1NFvFMPEWVli+rXXSZO7yOoZIaTs=,iv:yvIW+udsaoCDs675lpUFNaTwwz+AHQ7Vusq/RG0jExM=,tag:h446uV8zlZz8aRVa6n6AJQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
