apiVersion: v1
data:
    API_SERVER_URL: ENC[AES256_GCM,data:xZ+YoLXeOTMp7vgwFeTGTgafABg=,iv:PGvXpVSiWUg5Os87x4ERkoN47vPRsI7Cb4YGSsohveU=,tag:yWWgFAp7EGRXorRu4imRBA==,type:str]
    AUTH_GOOGLE_ID: ENC[AES256_GCM,data:SAQ/ifNTx20ymFpg3NJSO3+cbRH4yIY1E8pw1q4voN5tnksZOTscc61GFQFy7sdCE3dZeNWPt+hLQ9AUjBJqJ0iueB4SJVhhfoDBvj1br8vQx3o7knXWVX0UKyIm7XoG,iv:8DvSrK6uD1KedCqr8S9Qpdzp1iTXufII6/Vx6qVZnW8=,tag:MEIummBv3AvBKIJ2huNvkQ==,type:str]
    AUTH_GOOGLE_SECRET: ENC[AES256_GCM,data:ATD5J7hG3v3cKPT08DP8cZhB79Emy79ayVKHU0LvyBBvZQxDwKNcMftMRoQjQQZd,iv:wO6B+PeEnD4wJwNtSIHiGCOICsswmgkyu2gj+Ek0mmU=,tag:FdzWPl0wLEtGGMkxznGrzg==,type:str]
    AUTH_SECRET: ENC[AES256_GCM,data:h3Mjk/o93CDdbsvr2VqtvPeEs5wc7LLznWDAZlbXQqKNGmpQ7IsqqNpNZNz4l46btBtLQh4aFRlyaPwF,iv:cbSBwG5vFFe3bjqk5twSZvkVKcltHIjDCTWFtnSlwZQ=,tag:wtdqDTJ8VHGIQXc1ktWGnQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: web-env
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wgsnca8gljfz2659cs8rmme7aanwznkdakck32qmeks7sslec50svgdjwv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzY0QzVFJNcmZ5V3NPQ3Yy
            bkNFT3YrTEp1T0cvRHNXYkhGMUxUN0htNlR3Ck41T2ZIQ051V3Y1cEZ2OEVZNzBS
            eEJGVWNORVkzZTFzbmI3emtVRnZicFEKLS0tIDI1N0VzNlNieklxZGlYWGpORzVI
            WjFNbWVQd0l3dlRxQjIxcUNkSG16ZjgKsg4zB10NrBKsS38zUG++Ykeky5sB1/8m
            XcoO7+oLQIfJFzAdQrCV9jdsWfL/RqAWAxnwc8EbO0rdJS33eMCbIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-01T17:58:16Z"
    mac: ENC[AES256_GCM,data:RS+uGcR2JrUYRmW15lIuM3NKzg0/CsTZjxvVsXxgktXN4pgjSi4NZMbFdrZK7LQ3/BBzTszWqMfV6Sqq0Om1BG01lt8BXQ4QTH2H45ky3LnBGd7JkOS3sLUp9yawEo34DC31/KSDuVAy7nvz2wrPBfLH916z1ynjtbqQz/tVI54=,iv:E5/SkWnAwYkviry1saiR8W8ehfg1lYj8kH3X8vjkbh4=,tag:2AkRGZX+7KvQ9AbzC9ec4A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
